"""Add reset_otp columns

Revision ID: 66483260645b
Revises: 8e23cf1c820c
Create Date: 2026-06-24 14:15:17.285336+00:00
"""
from typing import Sequence, Union
from alembic import op
import sqlalchemy as sa


revision: str = '66483260645b'
down_revision: Union[str, None] = '8e23cf1c820c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None

def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('reset_otp', sa.String(length=6), nullable=True))
    op.add_column('users', sa.Column('reset_otp_expiry', sa.DateTime(timezone=True), nullable=True))
    # ### end Alembic commands ###

def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'reset_otp_expiry')
    op.drop_column('users', 'reset_otp')
    # ### end Alembic commands ###
